version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Set up golang building environment
          command: sudo apt install -y wget;wget https://dl.google.com/go/go1.12.6.linux-amd64.tar.gz;sudo tar -C /usr/local -xzf go1.12.6.linux-amd64.tar.gz

      - run:
          name: Set up c/cpp building environment
          command: sudo apt install -y cmake make gcc g++